### ISSUE TITLE
Uploads of music in YouTube music unavailable via YouTube api

### ISSUE THREAD

**Issue by stboch** [KoljaWindeler/ytube_music_player#12]
The existing method to get youtube urls only works from music released via YouTube Music. Music uploaded via the music app return as unplayable on the YouTube site. 

@KoljaWindeler at first pass looked at seeing if I could change the url to the music.youtube site instead of just YouTube while the js base is the same the regex used to find the cipher code might need to be adjusted to this new site. Was going to do more debugging and digging and see if I can get it working

**Comment by KoljaWindeler** [comment]
Ah, ok that explains this issue https://community.home-assistant.io/t/youtube-music-media-browser/226367/99?u=jkw right? 
I guess many user will never see that issue because they simply stream from YouTube and never upload songs. But please go on and have a look if you can optimize it.

**Comment by tprelog** [comment]
I think it should be pointed out explicitly that it is not working

> I guess many user will never see that issue because they simply stream from YouTube

95% of the time, this is the category I fall into so I made the same assumption with gmusic

While playback of uploaded music did work, there was never any album art. I figured it would mostly go unnoticed but I was surprised how many times that it got brought to my attention.

If this is possible to support, It would be great to see this added. While I only enjoy the benefit of listening to uploaded music that is not normally available, I came to realize there are many users who only used Google Music because of the ability to upload and listen their own music

**Comment by stboch** [comment]
Worked out a fix that will get the url provided by the youtube music api and not youtube this works for private audio media as the non-ciphered URLs are provided.

**Comment by stboch** [comment]
Created PR [13](https://github.com/KoljaWindeler/ytube_music_player/pull/13) with the changes

**Comment by stboch** [comment]
PR Merged Issue Closed
