### ISSUE TITLE
DLNA DMR Support?

### ISSUE THREAD

**Issue by mooton85** [KoljaWindeler/ytube_music_player#187]
**Is your feature request related to a problem? Please describe.**
I purchased an audiocast unit to use with my ceiling speakers (https://audiocast.io/) which uses LinkPlay and DLNA protocols. 

I have successfully integrated it into HA using the DLNA DMR integration. However, although playing local files, tts works ok when I try to play music via the ytube component, nothing plays. I am assuming (rightly or wrongly) that this isn't a setup issue or bug and would be a new feature.

**Describe the solution you'd like**
Support for playing media via the DLNA DMR component

**Describe alternatives you've considered**
Use the LinkPlay protocol instead but as youtube music is not natively supported, I think this would be more difficult.

**Comment by mistamal** [comment]
Hello! I am also having the same issue :( The configuration seems to be working since I can see my liked songs etc. The DLNA receiver (WiiM) is correctly set up and recognised, but no audio is output when I press play (I don't see a scrubbing bar either with the seconds lapsed). I tested the DLNA receiver by uploading a file to the HA docker and playing it to the DLNA receiver, which worked just fine. The ytube logs don't indicate any particular errors, and state that the tracks are being played/paused correctly.
Thank you very much for your hard and much appreciated work so far!!

**Comment by KoljaWindeler** [comment]
please try https://github.com/KoljaWindeler/ytube_music_player?tab=readme-ov-file#method-2-owntone-server-as-proxy
