### ISSUE TITLE
latest update broke input_select.ytube_music_player_playlist

### ISSUE THREAD

**Issue by catohagen** [KoljaWindeler/ytube_music_player#296]
the input_select for playlist just says 'loading' now, before it was working perfectly....

is there some easy way I can return to the previous version ?

Also the card, custom:polr-ytube-playing-card doesnt work anymore....playlist just say ' Unknown Error'

edit, ah wait....im running 20240103.01
I will update to the newest when its available from ha

**Comment by KoljaWindeler** [comment]
hi, so this happened for you and here https://github.com/KoljaWindeler/ytube_music_player/issues/297
I'm downgraded to 20240101.01, removed all ytmusicplayer, restarted HA, created a new ytmusicplayer without touching the advance options page .. input selects are loaded .. as expected .. 

This is due to having default values in the config flow, so even without setting the 'input_select.ytube_music_player_playlist' it is automatically set and update.

I see this in the debug log 
```
[custom_components.ytube_music_player.media_player] YtubeMediaPlayer config: 
[custom_components.ytube_music_player.media_player] - Header path: /config/.storage/ytube_header.json
[custom_components.ytube_music_player.media_player] - playlist: input_select.ytube_music_player_playlist
[custom_components.ytube_music_player.media_player] - mediaplayer: input_select.ytube_music_player_speakers
[custom_components.ytube_music_player.media_player] - source: input_select.ytube_music_player_source
[custom_components.ytube_music_player.media_player] - speakerlist: ['media_player.ab4f57da_d5e2a51e']
[custom_components.ytube_music_player.media_player] - playModes: input_select.ytube_music_player_playmode
[custom_components.ytube_music_player.media_player] - playContinuous: input_boolean.ytube_music_player_playcontinuous
[custom_components.ytube_music_player.media_player] - shuffle: True
[custom_components.ytube_music_player.media_player] - shuffle_mode: 1
[custom_components.ytube_music_player.media_player] - like_in_name: False
[custom_components.ytube_music_player.media_player] - track_limit: 25
[custom_components.ytube_music_player.media_player] - legacy_radio: True
```

after that I've updated to 20240112.01 and restarted HA. It still came up with the exact same log as above and .. all input select fields are updated as well.

If I go to settings -> ytubemusicplayer and click "configure" on the previously created entity I get this

![image](https://github.com/KoljaWindeler/ytube_music_player/assets/471314/55f31336-e061-469b-838c-2e900a9292c4)


so the values, that were set in 20240101 are still in the configuration and although 20240112 is not setting them by default they retain. 

If I remove the entity now, and create a new one, without going to advance settings .. then the default will NOT be set (this is new in 20240112). The input_select is still filled (from the last entity) but after a reboot it stays at loading.

So I have a hard time to replicated the bug. Did you recreate the entity after updating to 20240112? Can you check the debug log and check if the input_select fields are populated in the entitiy configuration

Thanks

**Comment by XalaTheShepard** [comment]
I have removed the integration, rebooted HA and reinstalled the integration. 
Will try the above mentioned solution when I arrive home, but in my case my speakers also don't load. So my situation is a bit more complicated

**Comment by catohagen** [comment]
@KoljaWindeler 
Thank you for looking into this... .I didnt manage to fix with updating or downgrading version, but I removed the integration
and reinstalled, and everything is working again. I'm still using the input_selects, but 

`PS: I'd highly recommend to move away from the input_select's anyway .. it was the initial way but media_browser, polr-ytube-media-card and mini_media_player offer way better UI if you ask me.`
i will try again, and without using input_selects

Thank you.

**Comment by KoljaWindeler** [comment]
Awesome.

It would have been interesting to see the log before fixing the issue .. I still don't get why the selects don't load.

So if someone sees the same issue, please copy the debug log (see Readme) before fixing it with a reconfiguration. 

Thanks

**Comment by XalaTheShepard** [comment]
I hope to provide you with the logs this evening , tomorrow at latest.

**Comment by XalaTheShepard** [comment]
[home-assistant_2024-01-14T10-35-44.989Z.log](https://github.com/KoljaWindeler/ytube_music_player/files/13931118/home-assistant_2024-01-14T10-35-44.989Z.log)

Dear all, 

Please find enclosed the logs. 

Only one error with the Ytube music player mentioned, but maybe another integration might be causing the issue. 

Kind regards and enjoy your Sunday, 

Robin De Becker

**Comment by KoljaWindeler** [comment]
Interesting. The fields are indeed blank. Can you go to integration -> ytubemusicplayer and click configure on the entity. Please post a screenshot from the advance page.
Thanks

**Comment by XalaTheShepard** [comment]
![Screenshot_20240114_120713_io homeassistant companion android](https://github.com/KoljaWindeler/ytube_music_player/assets/69390987/ffca7d08-a1c3-4cb0-9134-1f23c781b980)
![Screenshot_20240114_120704_io homeassistant companion android](https://github.com/KoljaWindeler/ytube_music_player/assets/69390987/89660c8d-2920-405c-b13c-0a2582667fc8)

**Comment by XalaTheShepard** [comment]
Thanks for the swift reply. 
Please find enclosed the screenshots

**Comment by KoljaWindeler** [comment]
ok, and is it working again once you add the entity_id of the input_selects?
![image](https://github.com/KoljaWindeler/ytube_music_player/assets/471314/6487b5ef-d893-41ee-b24a-1ab1e4107b78)

**Comment by XalaTheShepard** [comment]
Many thanks.
With adding these input selects everything works again.
Somehow wondering how they got erased.

Tried the card you mentioned above.
It is nice and beautiful, but still prefer the input select. It keeps track of your playlist, whereas the card always goes to the default overview and forces me to use 3 columns instead of 4.

Many thanks for the support.

Kind regards,

Robin

**Comment by KoljaWindeler** [comment]
Still wondering why it got erased but happy that you were able to fix it that easily
