### ISSUE TITLE
music stops after 19 minutes and 10 seconds

### ISSUE THREAD

**Issue by Stephan296** [KoljaWindeler/ytube_music_player#70]
When i play a long youtube song, for example a live set made by a DJ, the music stops at 19:10.

**Comment by stboch** [comment]
I wonder if this is due to the stream url timeout after 15 minutes and not the entire song is buffered in that time window. will try it on my end here...

**Comment by Stephan296** [comment]
Found another one, when i press on pause he goes to the next song. When i press pause again he will pause the music.

**Comment by KoljaWindeler** [comment]
How does your setup look like? What kind of output do you use? E.g. chromecast or sonos? Can you play more then 19:10 if you skip forward? E.g. start at 0:00 and instantly skip to 15:00. Will it stop again at 19:10?

**Comment by Stephan296** [comment]
yes i can play more then 19:10. when i select 15:00 he plays more then 19.10

**Comment by KoljaWindeler** [comment]
Ok so with sonos that is the expected behavior. The sonos will go to "pause" at the end of a track .. when I see a "pause" state I have to go to the next track ... So pause doesn't work for sonos and probably never will ... What I don't understand is the 19:10 ... So maybe the url isn't valid anymore after 19:10, but you are using the proxy, right? That should have downloaded the complete song ..

**Comment by Stephan296** [comment]
yes i use the proxy, it looks like he downloaded the whole song because when i select 25:00 min he plays from there and for example i click at 32:15 he plays also. I dont understand ;-)

**Comment by KoljaWindeler** [comment]
Neat ... So this might actually be a bug after all could you please enable debug log (see readme) and post the log part around 19:10 here

**Comment by KoljaWindeler** [comment]
Is this still a issue?
