### ISSUE TITLE
The 'NoneType' Error

### ISSUE THREAD

**Issue by RyanWoirol** [KoljaWindeler/ytube_music_player#73]
I am currently trying to get this guy to work and am coming across this error.

Let me know if you need further info.

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/ytube_music_player/media_player.py:328
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 12:21:56 AM (2 occurrences)
Last logged: 12:25:45 AM

[1888028632] 'NoneType' object has no attribute 'state'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 141, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1488, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1523, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 642, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 681, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 679, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 552, in async_turn_on
    await self.hass.async_add_executor_job(self.turn_on)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ytube_music_player/media_player.py", line 328, in turn_on
    playlist  = self.hass.states.get(self._select_playlist).state
AttributeError: 'NoneType' object has no attribute 'state'

**Comment by KoljaWindeler** [comment]
amazing .. so you turned on the player and got that error .. 

that means that your __select_playlist_ is not empty (otherwise [this](https://github.com/KoljaWindeler/ytube_music_player/blob/cda5e4493983729b0146d7b4139d76bd94f6ef3a/custom_components/ytube_music_player/media_player.py#L319) would catch it) .. ok .. so likely you don't have a drop down in your setup .. which is find, it should work without.

During the startup the component should have checked the existence and set the  __select_playlist_ to nothing if it doesn't exist. 

**did you maybe hit the turn_on BEFORE homeassistant was loaded completely?** 

otherwise:
1. Please [enable DEBUG messages](https://github.com/KoljaWindeler/ytube_music_player#1-reroute-debug-output-to-error-via-service)
2. call the ytube_music_player.call_method with command "**reload_dropdowns**"
3.  copy the resulting message to this ticket

Thanks, Kolja

**Comment by RyanWoirol** [comment]
I'm at work right now and they have blocked github, go figure.  I'm also like 70% comfortable and familiar with what I'm doing, ha.  Anyway, after following those instructions, this is an error I got. 

Logger: custom_components.ytube_music_player.media_player
Source: custom_components/ytube_music_player/media_player.py:147
Integration: yTubeMediaPlayer (documentation, issues)
First occurred: 7:34:33 AM (127 occurrences)
Last logged: 7:39:30 AM

TURNON
no or wrong playlist select field in the config, exiting
_turn_off_media_player
_sync_player
media_player.radio_speaker

**Comment by KoljaWindeler** [comment]
Jep, that happens if you simply turn on the player and it doesn't know what to play. 
You can either choose the music via the music browser or add the drop down fields. Checkout the video tutorials in the readme

**Comment by RyanWoirol** [comment]
I have been selecting music from the media browser first.  But nothing plays or starts to play.  It loads up on the card but nothing beyond that.

Sent from my Galaxy Note10+

________________________________

**Comment by KoljaWindeler** [comment]
Ok could you paste a log covering the attempt?

**Comment by RyanWoirol** [comment]
It is working after a HA reset.

Thank you for your help.
